version: "3.9"

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/postgres
      API_KEY: root
    networks:
      - my_network
    depends_on:
      db:
        condition: service_healthy
    command: /bin/bash -c "alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  seed:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/postgres
      API_KEY: root
    networks:
      - my_network
    depends_on:
      db:
        condition: service_healthy
    command: ["poetry", "run", "python", "seed.py"]

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge